name: AndroidBuild
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build With Gradle
        run: ./gradlew build --stacktrace

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: MovieApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
g