name: AndroidBuild
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Sync Gradle
        run: ./gradlew --refresh-dependencies

      - name: Build Free Variant
        run: ./gradlew assembleFreeDebug --stacktrace

      - name: Build Paid Variant
        run: ./gradlew assemblePaidDebug --stacktrace

      - name: Upload Free Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: MovieAppFree.apk
          path: app/build/outputs/apk/free/debug/app-free-debug.apk


